config/routes.rb
Rails.application.routes.draw do
  resources :teacher_registrations
  get 'welcome/index'

  devise_for :users
  root 'welcome#index'

  resources :lecture_comments
  resources :lectures
  resources :student_registrations
  resources :seminars

end

app/models/student_registration.rb
class StudentRegistration < ActiveRecord::Base
  belongs_to :user
  belongs_to :seminar
end

app/controllers/student_registrations_controller.rb
class StudentRegistrationsController < ApplicationController
  before_action :set_student_registration, only: [:show, :edit, :update, :destroy]

  # GET /student_registrations
  # GET /student_registrations.json
  def index
    @student_registrations = StudentRegistration.all
  end

  # GET /student_registrations/1
  # GET /student_registrations/1.json
  def show
  end

  # GET /student_registrations/new
  def new
    @student_registration = StudentRegistration.new
  end

  # GET /student_registrations/1/edit
  def edit
  end

  # POST /student_registrations
  # POST /student_registrations.json
  def create
    @student_registration = StudentRegistration.new(student_registration_params)

    respond_to do |format|
      if @student_registration.save
        format.html { redirect_to @student_registration, notice: 'Student registration was successfully created.' }
        format.json { render :show, status: :created, location: @student_registration }
      else
        format.html { render :new }
        format.json { render json: @student_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_registrations/1
  # PATCH/PUT /student_registrations/1.json
  def update
    respond_to do |format|
      if @student_registration.update(student_registration_params)
        format.html { redirect_to @student_registration, notice: 'Student registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_registration }
      else
        format.html { render :edit }
        format.json { render json: @student_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_registrations/1
  # DELETE /student_registrations/1.json
  def destroy
    @student_registration.destroy
    respond_to do |format|
      format.html { redirect_to student_registrations_url, notice: 'Student registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_registration
      @student_registration = StudentRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_registration_params
      params.require(:student_registration).permit(:user_id, :seminar_id)
    end
end

app/helpers/student_registrations_helper.rb
module StudentRegistrationsHelper
end

app/views/student_registrations/_form.html.erb
<%= form_for(@student_registration) do |f| %>
  <% if @student_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_registration.errors.count, "error") %> prohibited this student_registration from being saved:</h2>

      <ul>
      <% @student_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :seminar_id %><br>
    <%= f.text_field :seminar_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_registrations/edit.html.erb
<h1>Editing Student Registration</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_registration %> |
<%= link_to 'Back', student_registrations_path %>

app/views/student_registrations/index.html.erb
<h1>Listing Student Registrations</h1>

<table class="table table-bordered table-hover table-sm">
  <thead>
    <tr>
      <th>User</th>
      <th>Seminar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_registrations.each do |student_registration| %>
      <tr>
        <td><%= student_registration.user.try(:email) %></td>
        <td><%= link_to student_registration.seminar.try(:name), seminar_path(student_registration.seminar) %></td>
        <td><%= link_to 'Show', student_registration %></td>
        <td><%= link_to 'Edit', edit_student_registration_path(student_registration) %></td>
        <td><%= link_to 'Destroy', student_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student registration', new_student_registration_path %>

app/views/student_registrations/new.html.erb
<h1>New Student Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', student_registrations_path %>

app/views/student_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @student_registration.user %>
</p>

<p>
  <strong>Seminar:</strong>
  <%= @student_registration.seminar %>
</p>

<%= link_to 'Edit', edit_student_registration_path(@student_registration) %> |
<%= link_to 'Back', student_registrations_path %>