config/routes.rb
Rails.application.routes.draw do
  resources :teacher_registrations
  get 'welcome/index'

  devise_for :users
  root 'welcome#index'

  resources :lecture_comments
  resources :lectures
  resources :student_registrations
  resources :seminars

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <%= link_to "BetriMenntun", welcome_index_path, class: "navbar-brand"  %>
  <ul class="nav navbar-nav">
    <li class="nav-item ">
    </li>
    <li class="nav-item <%= 'active' if current_page?(lectures_path) %>">
      <%= link_to 'Lectures', lectures_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= 'active' if current_page?(lecture_comments_path) %>">
      <%= link_to 'Lecture Comments', lecture_comments_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= 'active' if current_page?(seminars_path) %>">
      <%= link_to 'Seminars',         seminars_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= 'active' if current_page?(student_registrations_path) %>">
      <%= link_to 'Student Reg',      student_registrations_path, class: "nav-link" %>
    </li>
    <li class="nav-item <%= 'active' if current_page?(teacher_registrations_path) %>">
      <%= link_to 'Teacher Reg',      teacher_registrations_path , class: "nav-link" %>
    </li>
    <li class="nav-item">
      <form class="form-inline ">
        <input class="form-control" type="text" placeholder="Search">
        <button class="btn btn-success-outline" type="submit">Search</button>
      </form>
    </li>
  </ul>
  <ul class="nav navbar-nav pull-xs-right">

    <% if user_signed_in? %>
      <li class="nav-item ">
        <%= link_to current_user.email, edit_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "log out", destroy_user_session_path, method: :delete , class:"nav-link"%>
      </li>
    <% else %>
      <li class="nav-item ">
        <%= link_to "Login", new_user_session_path, class:"nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
      </li>
    <% end %>

  </ul>
</nav>