config/routes.rb
Rails.application.routes.draw do
  resources :teacher_registrations
  get 'welcome/index'

  devise_for :users
  root 'welcome#index'

  resources :lecture_comments
  resources :lectures
  resources :student_registrations
  resources :seminars

end

app/models/seminar.rb
class Seminar < ActiveRecord::Base
end

app/controllers/seminars_controller.rb
class SeminarsController < ApplicationController
  before_action :set_seminar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /seminars
  # GET /seminars.json
  def index
    @seminars = Seminar.all
  end

  # GET /seminars/1
  # GET /seminars/1.json
  def show
    @students = StudentRegistration.where(:seminar_id => @seminar.id)
  end

  # GET /seminars/new
  def new
    @seminar = Seminar.new
  end

  # GET /seminars/1/edit
  def edit
  end

  # POST /seminars
  # POST /seminars.json
  def create
    @seminar = Seminar.new(seminar_params)

    respond_to do |format|
      if @seminar.save
        format.html { redirect_to @seminar, notice: 'Seminar was successfully created.' }
        format.json { render :show, status: :created, location: @seminar }
      else
        format.html { render :new }
        format.json { render json: @seminar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seminars/1
  # PATCH/PUT /seminars/1.json
  def update
    respond_to do |format|
      if @seminar.update(seminar_params)
        format.html { redirect_to @seminar, notice: 'Seminar was successfully updated.' }
        format.json { render :show, status: :ok, location: @seminar }
      else
        format.html { render :edit }
        format.json { render json: @seminar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seminars/1
  # DELETE /seminars/1.json
  def destroy
    @seminar.destroy
    respond_to do |format|
      format.html { redirect_to seminars_url, notice: 'Seminar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seminar
      @seminar = Seminar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seminar_params
      params.require(:seminar).permit(:name, :active, :visible)
    end
end

app/helpers/seminars_helper.rb
module SeminarsHelper
end

app/views/seminars/_form.html.erb
<%= form_for(@seminar) do |f| %>
  <% if @seminar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seminar.errors.count, "error") %> prohibited this seminar from being saved:</h2>

      <ul>
      <% @seminar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seminars/edit.html.erb
<h1>Editing Seminar</h1>

<%= render 'form' %>

<%= link_to 'Show', @seminar %> |
<%= link_to 'Back', seminars_path %>

app/views/seminars/index.html.erb
<h1>Listing Seminars</h1>

<table class="table table-bordered table-hover table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seminars.each do |seminar| %>
      <tr>
        <td><%= link_to seminar.name, seminar %></td>
        <td><%= seminar.active %></td>
        <td><%= seminar.visible %></td>
        <td><%= link_to 'Show', seminar %></td>
        <td><%= link_to 'Edit', edit_seminar_path(seminar) %></td>
        <td><%= link_to 'Destroy', seminar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seminar', new_seminar_path %>

app/views/seminars/new.html.erb
<h1>New Seminar</h1>

<%= render 'form' %>

<%= link_to 'Back', seminars_path %>

app/views/seminars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @seminar.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @seminar.active %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @seminar.visible %>
</p>

<%= link_to 'Edit', edit_seminar_path(@seminar) %> |
<%= link_to 'Back', seminars_path %>

<hr />

<h4>Students in this seminar:</h4>
<p>Can we call student_registration/index and but only for this seminars id?</p>

<% @students.each do |s| %>
  <%= link_to s.user.email, s %>
  <br />
<% end %>

<h4>Lectures in this seminar:</h4>

<hr />